=== HectorBoreas/Lenguaje_Marcas/UT4_XML/XLS/catalogo2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsi:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xsi:annotation>
        <xsi:documentation>
            Define una biblioteca compuesta por libros que pueden tener
            m√∫ltiples autores y deja como opcional la editorial.
        </xsi:documentation>
    </xsi:annotation>
    <xsi:element name="catalogo">
        <xsi:complexType>
            <xsi:sequence>           
                <xsi:element name="producto" maxOccurs="unbounded">
                    <xsi:complexType>
                        <xsi:sequence>
                            <xsi:element name="nombre">
                                <xsi:simpleType>
                                    <xsi:restriction base="xsi:string">
                                        <xsi:maxLength value="25"/>
                                    </xsi:restriction>
                                </xsi:simpleType>
                            </xsi:element>
                            <xsi:element name="precio">
                                <xsi:simpleType>
                                    <xsi:restriction base="xsi:decimal">
                                        <xsi:maxInclusive value="10000"/>
                                    </xsi:restriction>
                                </xsi:simpleType>
                            </xsi:element>
                            <xsi:element name="categoria">
                                <xsi:simpleType>
                                    <xsi:restriction base="xsi:string">
                                        <xsi:pattern value="C.*"/>
                                    </xsi:restriction>
                                </xsi:simpleType>
                            </xsi:element>
                        </xsi:sequence>
                        <xsi:attribute name="cod" type="xsi:string"/>
                    </xsi:complexType>
                </xsi:element>
            </xsi:sequence>
        </xsi:complexType>
    </xsi:element>
</xsi:schema>

=== HectorBoreas/Lenguaje_Marcas/UT4_XML/XLS/catalogo.xml
<?xml version="1.0" encoding="UTF-8"?>
<catalogo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="catalogo2.xsd">
    <producto>
        <nombre>Teléfono Móvil</nombre>
        <precio>299.99</precio>
        <categoria>CEletrónica</categoria>
    </producto>
    <producto>
        <nombre>Impresora 3D</nombre>
        <precio>1499.99</precio>
        <categoria>CImpresión</categoria>
    </producto>
</catalogo>
