=== HectorBoreas/Lenguaje_Marcas/UT4_XML/XLS/coches2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsi:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xsi:annotation>
        <xsi:documentation>
            Define un catalogo de coches de un concesionario.
        </xsi:documentation>
    </xsi:annotation>
    <xsi:element name="coches">
        <xsi:complexType>
            <xsi:sequence>           
                <xsi:element name="coche" maxOccurs="unbounded">
                    <xsi:complexType>
                        <xsi:sequence>
                            <xsi:element name="modelo" type="xsi:string"/>
                            <xsi:element name="velocidad">
                                <xsi:simpleType>
                                    <xsi:restriction base="xsi:positiveInteger">
                                        <xsi:maxInclusive value="250"/>
                                    </xsi:restriction>
                                </xsi:simpleType>
                            </xsi:element>
                            <xsi:element name="puertas">
                                <xsi:simpleType>
                                    <xsi:restriction base="xsi:positiveInteger">
                                        <xsi:minInclusive value="2"/>
                                        <xsi:maxInclusive value="5"/>
                                    </xsi:restriction>
                                </xsi:simpleType>
                            </xsi:element>
                            <xsi:element name="color">
                                <xsi:complexType>
                                    <xsi:simpleContent>
                                        <xsi:extension base="xsi:string">
                                            <xsi:attribute name="metalizado" use="required">
                                                <xsi:simpleType>
                                                    <xsi:restriction base="xsi:string">
                                                        <xsi:enumeration value="si"/>
                                                        <xsi:enumeration value="no"/>
                                                    </xsi:restriction>
                                                </xsi:simpleType>
                                            </xsi:attribute>
                                        </xsi:extension>
                                    </xsi:simpleContent>                                    
                                </xsi:complexType>
                            </xsi:element>
                            <xsi:element name="precio" type="xsi:positiveInteger"/>
                            <xsi:element name="fecha_lanzamiento" type="xsi:date"/>
                        </xsi:sequence>
                        <xsi:attribute name="tipo" type="xsi:string" use="required"/>
                        <xsi:attribute name="id" use="required">
                            <xsi:simpleType>
                                <xsi:restriction base="xsi:string">
                                    <xsi:pattern value="C.*"/>
                                </xsi:restriction>
                            </xsi:simpleType>
                        </xsi:attribute>
                    </xsi:complexType>
                </xsi:element>
            </xsi:sequence>
        </xsi:complexType>
    </xsi:element>
</xsi:schema>

=== HectorBoreas/Lenguaje_Marcas/UT4_XML/XLS/coches.xml
<?xml version="1.0" encoding="UTF-8"?>
<coches xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="coches2.xsd">
    <coche tipo="Deportivo" id="C001">
        <modelo>Ferrari F8</modelo>
        <velocidad>250</velocidad>
        <puertas>2</puertas>
        <color metalizado="si">Rojo</color>
        <precio>250000</precio>
        <fecha_lanzamiento>2020-03-05</fecha_lanzamiento>
    </coche>
    <coche tipo="SUV" id="C002">
        <modelo>Range Rover Evoque</modelo>
        <velocidad>220</velocidad>
        <puertas>5</puertas>
        <color metalizado="no">Negro</color>
        <precio>60000</precio>
        <fecha_lanzamiento>2022-09-12</fecha_lanzamiento>
    </coche>
    <coche tipo="SedÃ¡n" id="C003">
        <modelo>BMW serie 5</modelo>
        <velocidad>250</velocidad>
        <puertas>3</puertas>
        <color metalizado="si">Gris</color>
        <precio>100000</precio>
        <fecha_lanzamiento>2019-02-13</fecha_lanzamiento>
    </coche>
</coches>
